In [111]:
# import required library(s)

import pandas as pd

In [ ]:
# Load all .csv files into separate dataframes

df_customers_part1 = pd.read_csv("../data/customers_part1.csv")
df_customers_part2 = pd.read_csv("../data/customers_part2.csv")
df_customers = pd.read_csv("../data/customers.csv")
df_order_items = pd.read_csv("../data/order_items.csv")
df_orders = pd.read_csv("../data/orders.csv")
df_products = pd.read_csv("../data/products.csv")

In [ ]:
# Preview and basic inspection for each dataframe

df_customers_part1

     customer_id  customer_name          city membership
0              1  Customer_0001      New York     Bronze
1              2  Customer_0002   San Antonio     Bronze
2              3  Customer_0003  Philadelphia     Bronze
3              4  Customer_0004       Houston     Silver
4              5  Customer_0005       Houston     Silver
..           ...            ...           ...        ...
495          496  Customer_0496       Houston     Silver
496          497  Customer_0497      New York     Silver
497          498  Customer_0498   Los Angeles       Gold
498          499  Customer_0499     San Diego     Bronze
499          500  Customer_0500       Houston       Gold

[500 rows x 4 columns]

In [5]:
df_customers_part1.info()
df_customers_part1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    500 non-null    int64
 1   customer_name  500 non-null    object
 2   city           500 non-null    object
 3   membership     500 non-null    object
dtypes: int64(1), object(3)
memory usage: 15.8+ KB

       customer_id
count   500.000000
mean    250.500000
std     144.481833
min       1.000000
25%     125.750000
50%     250.500000
75%     375.250000
max     500.000000

In [6]:
df_customers_part2

     customer_id  customer_name          city membership
0            501  Customer_0501      New York       Gold
1            502  Customer_0502  Philadelphia     Silver
2            503  Customer_0503     San Diego       Gold
3            504  Customer_0504   San Antonio       Gold
4            505  Customer_0505   Los Angeles     Silver
..           ...            ...           ...        ...
495          996  Customer_0996  Philadelphia     Silver
496          997  Customer_0997       Phoenix     Bronze
497          998  Customer_0998   Los Angeles     Silver
498          999  Customer_0999     San Diego     Silver
499         1000  Customer_1000       Phoenix     Silver

[500 rows x 4 columns]

In [7]:
df_customers_part2

     customer_id  customer_name          city membership
0            501  Customer_0501      New York       Gold
1            502  Customer_0502  Philadelphia     Silver
2            503  Customer_0503     San Diego       Gold
3            504  Customer_0504   San Antonio       Gold
4            505  Customer_0505   Los Angeles     Silver
..           ...            ...           ...        ...
495          996  Customer_0996  Philadelphia     Silver
496          997  Customer_0997       Phoenix     Bronze
497          998  Customer_0998   Los Angeles     Silver
498          999  Customer_0999     San Diego     Silver
499         1000  Customer_1000       Phoenix     Silver

[500 rows x 4 columns]

In [8]:
df_customers_part2.info()
df_customers_part2.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    500 non-null    int64
 1   customer_name  500 non-null    object
 2   city           500 non-null    object
 3   membership     500 non-null    object
dtypes: int64(1), object(3)
memory usage: 15.8+ KB

       customer_id
count   500.000000
mean    750.500000
std     144.481833
min     501.000000
25%     625.750000
50%     750.500000
75%     875.250000
max    1000.000000

In [9]:
df_customers

     customer_id  customer_name          city membership
0              1  Customer_0001      New York     Bronze
1              2  Customer_0002   San Antonio     Bronze
2              3  Customer_0003  Philadelphia     Bronze
3              4  Customer_0004       Houston     Silver
4              5  Customer_0005       Houston     Silver
..           ...            ...           ...        ...
995          996  Customer_0996  Philadelphia     Silver
996          997  Customer_0997       Phoenix     Bronze
997          998  Customer_0998   Los Angeles     Silver
998          999  Customer_0999     San Diego     Silver
999         1000  Customer_1000       Phoenix     Silver

[1000 rows x 4 columns]

In [10]:
df_customers.info()
df_customers.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    1000 non-null   int64
 1   customer_name  1000 non-null   object
 2   city           1000 non-null   object
 3   membership     1000 non-null   object
dtypes: int64(1), object(3)
memory usage: 31.4+ KB

       customer_id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [11]:
df_order_items

       order_item_id  order_id  product_id  quantity
0                  1     59445        1009         3
1                  2     61509        1122         2
2                  3     54992        1350         3
3                  4     66809        1423         5
4                  5     52461        1482         2
...              ...       ...         ...       ...
99995          99996     56011        1428         2
99996          99997     51475        1276         4
99997          99998     69525        1367         1
99998          99999     60133        1182         3
99999         100000     57570        1366         1

[100000 rows x 4 columns]

In [12]:
df_order_items.info()
df_order_items.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  100000 non-null  int64
 1   order_id       100000 non-null  int64
 2   product_id     100000 non-null  int64
 3   quantity       100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB

       order_item_id       order_id     product_id       quantity
count  100000.000000  100000.000000  100000.000000  100000.000000
mean    50000.500000   60016.464160    1250.514210       2.998250
std     28867.657797    5764.270419     144.334032       1.415093
min         1.000000   50001.000000    1001.000000       1.000000
25%     25000.750000   55039.000000    1126.000000       2.000000
50%     50000.500000   60026.000000    1250.000000       3.000000
75%     75000.250000   64991.000000    1375.000000       4.000000
max    100000.000000   70000.000000    1500.000000       5.000000

In [13]:
df_orders

       order_id  customer_id  order_date
0         50001          693  2025-07-11
1         50002          534  2025-02-01
2         50003          998  2025-11-14
3         50004          772  2025-02-16
4         50005           17  2025-11-15
...         ...          ...         ...
19995     69996          698  2025-05-01
19996     69997          472  2025-10-20
19997     69998          529  2025-12-08
19998     69999          652  2025-06-23
19999     70000          418  2025-09-11

[20000 rows x 3 columns]

In [14]:
df_orders.info()
df_orders.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     20000 non-null  int64
 1   customer_id  20000 non-null  int64
 2   order_date   20000 non-null  object
dtypes: int64(2), object(1)
memory usage: 468.9+ KB

           order_id   customer_id
count  20000.000000  20000.000000
mean   60000.500000    497.856900
std     5773.647028    288.095708
min    50001.000000      1.000000
25%    55000.750000    249.000000
50%    60000.500000    500.000000
75%    65000.250000    745.000000
max    70000.000000   1000.000000

In [15]:
df_products

     product_id  product_name     category    price
0          1001  Product_0001       Sports  1282.68
1          1002  Product_0002       Sports   407.06
2          1003  Product_0003        Books  1776.68
3          1004  Product_0004        Books  1624.45
4          1005  Product_0005       Sports   702.38
..          ...           ...          ...      ...
495        1496  Product_0496         Home   397.93
496        1497  Product_0497  Electronics   527.48
497        1498  Product_0498         Home  1255.77
498        1499  Product_0499  Electronics   779.37
499        1500  Product_0500         Home   694.04

[500 rows x 4 columns]

In [16]:
df_products.info()
df_products.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    int64
 1   product_name  500 non-null    object
 2   category      500 non-null    object
 3   price         500 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 15.8+ KB

        product_id        price
count   500.000000   500.000000
mean   1250.500000   978.846820
std     144.481833   580.835186
min    1001.000000     6.130000
25%    1125.750000   496.077500
50%    1250.500000   943.440000
75%    1375.250000  1496.190000
max    1500.000000  1999.530000

In [ ]:
# Analysis

# Find all customers whose membership is "Gold".

df_customers[df_customers['membership'] == 'Gold']

     customer_id  customer_name          city membership
9             10  Customer_0010      New York       Gold
10            11  Customer_0011       Phoenix       Gold
12            13  Customer_0013  Philadelphia       Gold
13            14  Customer_0014   San Antonio       Gold
15            16  Customer_0016   San Antonio       Gold
..           ...            ...           ...        ...
972          973  Customer_0973       Houston       Gold
981          982  Customer_0982  Philadelphia       Gold
983          984  Customer_0984  Philadelphia       Gold
985          986  Customer_0986  Philadelphia       Gold
990          991  Customer_0991   Los Angeles       Gold

[296 rows x 4 columns]

In [ ]:
# Find products whose price is greater than 500.

df_products[df_products['price'] > 500]

     product_id  product_name     category    price
0          1001  Product_0001       Sports  1282.68
2          1003  Product_0003        Books  1776.68
3          1004  Product_0004        Books  1624.45
4          1005  Product_0005       Sports   702.38
5          1006  Product_0006     Clothing  1159.33
..          ...           ...          ...      ...
494        1495  Product_0495        Books   774.91
496        1497  Product_0497  Electronics   527.48
497        1498  Product_0498         Home  1255.77
498        1499  Product_0499  Electronics   779.37
499        1500  Product_0500         Home   694.04

[374 rows x 4 columns]

In [19]:
# Find all orders made after 2025-06-01:

df_orders['order_date']= pd.to_datetime(df_orders['order_date'], format = '%Y-%m-%d')
df_orders[df_orders['order_date'] > '2025-06-01']

       order_id  customer_id order_date
0         50001          693 2025-07-11
2         50003          998 2025-11-14
4         50005           17 2025-11-15
5         50006          379 2025-10-05
6         50007          290 2025-12-12
...         ...          ...        ...
19994     69995          530 2025-12-20
19996     69997          472 2025-10-20
19997     69998          529 2025-12-08
19998     69999          652 2025-06-23
19999     70000          418 2025-09-11

[11729 rows x 3 columns]

In [ ]:
# Sort products by price descending.

df_products.sort_values(by = 'price', ascending = False)

     product_id  product_name     category    price
460        1461  Product_0461         Home  1999.53
105        1106  Product_0106     Clothing  1997.66
397        1398  Product_0398        Books  1988.57
111        1112  Product_0112       Sports  1987.08
357        1358  Product_0358        Books  1985.65
..          ...           ...          ...      ...
364        1365  Product_0365  Electronics    33.18
272        1273  Product_0273       Sports    32.49
201        1202  Product_0202        Books    29.04
160        1161  Product_0161  Electronics    26.98
86         1087  Product_0087  Electronics     6.13

[500 rows x 4 columns]

In [21]:
# Sort customers alphabetically by name.

df_customers.sort_values(by = 'customer_name')

     customer_id  customer_name          city membership
0              1  Customer_0001      New York     Bronze
1              2  Customer_0002   San Antonio     Bronze
2              3  Customer_0003  Philadelphia     Bronze
3              4  Customer_0004       Houston     Silver
4              5  Customer_0005       Houston     Silver
..           ...            ...           ...        ...
995          996  Customer_0996  Philadelphia     Silver
996          997  Customer_0997       Phoenix     Bronze
997          998  Customer_0998   Los Angeles     Silver
998          999  Customer_0999     San Diego     Silver
999         1000  Customer_1000       Phoenix     Silver

[1000 rows x 4 columns]

In [ ]:
# Set customer_id as index

df_customers.set_index('customer_id', inplace = False)

             customer_name          city membership
customer_id
1            Customer_0001      New York     Bronze
2            Customer_0002   San Antonio     Bronze
3            Customer_0003  Philadelphia     Bronze
4            Customer_0004       Houston     Silver
5            Customer_0005       Houston     Silver
...                    ...           ...        ...
996          Customer_0996  Philadelphia     Silver
997          Customer_0997       Phoenix     Bronze
998          Customer_0998   Los Angeles     Silver
999          Customer_0999     San Diego     Silver
1000         Customer_1000       Phoenix     Silver

[1000 rows x 3 columns]

In [ ]:
# Retrieve customer with ID 500.

df_customers[df_customers['customer_id'] == 500]

     customer_id  customer_name     city membership
499          500  Customer_0500  Houston       Gold

In [124]:
# Count customers per membership level.

df_membership_lvl_count = df_customers.groupby('membership').agg({'customer_id':['count']})
df_membership_lvl_count

           customer_id
                 count
membership
Bronze             307
Gold               296
Silver             397

In [ ]:
# Find average product price by category.

df_avg_price_per_category = df_products.groupby('category').agg({'price':['mean']})
df_avg_price_per_category

                   price
                    mean
category
Books         939.755806
Clothing      978.438468
Electronics  1049.730000
Home          941.956064
Sports        985.136486

In [125]:
# Find number of products per category.

df_num_products_per_category = df_products.groupby('category').agg({'product_id':['count']})
df_num_products_per_category

            product_id
                 count
category
Books               93
Clothing           111
Electronics         91
Home                94
Sports             111

In [ ]:
# Merge customers and orders

df_customers.merge(df_orders, on = 'customer_id')

       customer_id  customer_name      city membership  order_id order_date
0                1  Customer_0001  New York     Bronze     50583 2025-03-04
1                1  Customer_0001  New York     Bronze     51260 2025-04-25
2                1  Customer_0001  New York     Bronze     51802 2025-09-27
3                1  Customer_0001  New York     Bronze     52406 2025-05-16
4                1  Customer_0001  New York     Bronze     52506 2025-07-26
...            ...            ...       ...        ...       ...        ...
19995         1000  Customer_1000   Phoenix     Silver     65315 2025-12-25
19996         1000  Customer_1000   Phoenix     Silver     65570 2025-09-21
19997         1000  Customer_1000   Phoenix     Silver     66128 2025-05-20
19998         1000  Customer_1000   Phoenix     Silver     66317 2025-12-12
19999         1000  Customer_1000   Phoenix     Silver     69376 2025-02-24

[20000 rows x 6 columns]

In [28]:
# Merge order_items and products

df_order_items.merge(df_products, on = 'product_id')

,order_item_id,order_id,product_id,quantity,product_name,category,price
0,1,59445,1009,3,Product_0009,Sports,1806.27
1,2,61509,1122,2,Product_0122,Books,882.42
2,3,54992,1350,3,Product_0350,Sports,480.74
3,4,66809,1423,5,Product_0423,Sports,1007.85
4,5,52461,1482,2,Product_0482,Clothing,1312.64
...,...,...,...,...,...,...,...
99995,99996,56011,1428,2,Product_0428,Books,1648.71
99996,99997,51475,1276,4,Product_0276,Books,791.17
99997,99998,69525,1367,1,Product_0367,Sports,532.83
99998,99999,60133,1182,3,Product_0182,Electronics,1222.76
99999,100000,57570,1366,1,Product_0366,Sports,1855.70

In [ ]:
# Create a complete sales table by merging:
# customers
# orders
# order_items
# products

df_merge_customers_orders = df_customers.merge(df_orders, on = 'customer_id')
df_merge_order_items_products = df_order_items.merge(df_products, on = 'product_id')

In [ ]:
df_master_dataset = df_merge_customers_orders.merge(df_merge_order_items_products, on = 'order_id')

,customer_id,customer_name,city,membership,order_id,order_date,order_item_id,product_id,quantity,product_name,category,price
0,1,Customer_0001,New York,Bronze,50583,2025-03-04,29176,1280,3,Product_0280,Sports,1189.06
1,1,Customer_0001,New York,Bronze,50583,2025-03-04,58906,1004,4,Product_0004,Books,1624.45
2,1,Customer_0001,New York,Bronze,50583,2025-03-04,64660,1338,3,Product_0338,Electronics,700.98
3,1,Customer_0001,New York,Bronze,51260,2025-04-25,15161,1425,1,Product_0425,Sports,707.10
4,1,Customer_0001,New York,Bronze,51260,2025-04-25,35184,1426,1,Product_0426,Books,1133.75
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1000,Customer_1000,Phoenix,Silver,69376,2025-02-24,30388,1378,5,Product_0378,Home,659.21
99996,1000,Customer_1000,Phoenix,Silver,69376,2025-02-24,34705,1235,5,Product_0235,Home,1239.23
99997,1000,Customer_1000,Phoenix,Silver,69376,2025-02-24,41802,1069,4,Product_0069,Electronics,1000.89
99998,1000,Customer_1000,Phoenix,Silver,69376,2025-02-24,71679,1230,3,Product_0230,Books,434.41
99999,1000,Customer_1000,Phoenix,Silver,69376,2025-02-24,98710,1190,5,Product_0190,Books,89.89

In [34]:
# Using the master dataset:
# Calculate total sales per category. (Formula: price × quantity)

df_master_dataset['total_sales'] = df_master_dataset['price'] * df_master_dataset['quantity']
df_master_dataset.groupby('category').agg({'total_sales':'sum'})

             total_sales
category
Books        52456042.93
Clothing     64847035.12
Electronics  56921528.32
Home         53578536.46
Sports       66356844.05

In [ ]:
# Find top 10 selling products.

df_top_10_selling_products = df_master_dataset.groupby('product_name').agg({'total_sales':'sum'}).sort_values(by = 'total_sales', ascending = False).iloc[:10]
df_top_10_selling_products

              total_sales
product_name
Product_0461   1333686.51
Product_0307   1318478.80
Product_0112   1315446.96
Product_0383   1303938.86
Product_0465   1302640.60
Product_0106   1302474.32
Product_0170   1279281.63
Product_0008   1277753.31
Product_0113   1273525.80
Product_0200   1261904.60

In [ ]:
# Find top 10 customers by spending.

df_top_10_spenders = df_master_dataset.groupby('customer_name').agg({'total_sales':'sum'}).sort_values(by = 'total_sales', ascending = False).iloc[:10]
df_top_10_spenders

               total_sales
customer_name
Customer_0153    544534.24
Customer_0820    508138.24
Customer_0682    494642.76
Customer_0987    491830.70
Customer_0429    491301.92
Customer_0774    486489.85
Customer_0507    485254.68
Customer_0529    485043.28
Customer_0938    480381.87
Customer_0627    472751.90

In [ ]:
# Find sales by city.

df_sales_per_city = df_master_dataset.groupby('city').agg({'total_sales':'sum'})
df_sales_per_city

              total_sales
city
Chicago       36507521.31
Houston       37124248.64
Los Angeles   32943061.66
New York      38532231.46
Philadelphia  38177993.87
Phoenix       37138142.76
San Antonio   37975910.95
San Diego     35760876.23

In [ ]:
# Convert 'customer_id' to index in 'customers' and 'orders' dataframes.
# Use join() instead of merge().

df_join_customers_orders = df_customers.set_index('customer_id').join(df_orders.set_index('customer_id'))
df_join_customers_orders

             customer_name      city membership  order_id order_date
customer_id
1            Customer_0001  New York     Bronze     50583 2025-03-04
1            Customer_0001  New York     Bronze     51260 2025-04-25
1            Customer_0001  New York     Bronze     51802 2025-09-27
1            Customer_0001  New York     Bronze     52406 2025-05-16
1            Customer_0001  New York     Bronze     52506 2025-07-26
...                    ...       ...        ...       ...        ...
1000         Customer_1000   Phoenix     Silver     65315 2025-12-25
1000         Customer_1000   Phoenix     Silver     65570 2025-09-21
1000         Customer_1000   Phoenix     Silver     66128 2025-05-20
1000         Customer_1000   Phoenix     Silver     66317 2025-12-12
1000         Customer_1000   Phoenix     Silver     69376 2025-02-24

[20000 rows x 5 columns]

In [48]:
# Concatenate 'customers_part1.csv' and 'customers_part2.csv'
pd.concat([df_customers_part1, df_customers_part2], axis = 0)

     customer_id  customer_name          city membership
0              1  Customer_0001      New York     Bronze
1              2  Customer_0002   San Antonio     Bronze
2              3  Customer_0003  Philadelphia     Bronze
3              4  Customer_0004       Houston     Silver
4              5  Customer_0005       Houston     Silver
..           ...            ...           ...        ...
495          996  Customer_0996  Philadelphia     Silver
496          997  Customer_0997       Phoenix     Bronze
497          998  Customer_0998   Los Angeles     Silver
498          999  Customer_0999     San Diego     Silver
499         1000  Customer_1000       Phoenix     Silver

[1000 rows x 4 columns]

In [ ]:
# Split products by category and concatenate them back together.

# Products by 'Sports' category
df_sports_category = df_products[df_products['category'] == 'Sports']
df_sports_category

     product_id  product_name category    price
0          1001  Product_0001   Sports  1282.68
1          1002  Product_0002   Sports   407.06
4          1005  Product_0005   Sports   702.38
8          1009  Product_0009   Sports  1806.27
13         1014  Product_0014   Sports   184.55
..          ...           ...      ...      ...
480        1481  Product_0481   Sports   681.34
482        1483  Product_0483   Sports   192.57
489        1490  Product_0490   Sports  1076.66
491        1492  Product_0492   Sports   125.96
493        1494  Product_0494   Sports   512.83

[111 rows x 4 columns]

In [50]:
# Products by 'Clothing' category

df_clothing_category = df_products[df_products['category'] == 'Clothing']
df_clothing_category

     product_id  product_name  category    price
5          1006  Product_0006  Clothing  1159.33
10         1011  Product_0011  Clothing   667.67
17         1018  Product_0018  Clothing   152.75
20         1021  Product_0021  Clothing  1162.58
22         1023  Product_0023  Clothing  1263.67
..          ...           ...       ...      ...
475        1476  Product_0476  Clothing   510.35
481        1482  Product_0482  Clothing  1312.64
483        1484  Product_0484  Clothing  1899.95
486        1487  Product_0487  Clothing   277.26
492        1493  Product_0493  Clothing   740.91

[111 rows x 4 columns]

In [51]:
# Products by 'Electronics' category

df_electronics_category = df_products[df_products['category'] == 'Electronics']
df_electronics_category

     product_id  product_name     category    price
12         1013  Product_0013  Electronics   427.49
21         1022  Product_0022  Electronics  1549.96
23         1024  Product_0024  Electronics  1764.94
26         1027  Product_0027  Electronics  1426.94
33         1034  Product_0034  Electronics   311.30
..          ...           ...          ...      ...
463        1464  Product_0464  Electronics   967.34
485        1486  Product_0486  Electronics  1753.15
490        1491  Product_0491  Electronics   597.25
496        1497  Product_0497  Electronics   527.48
498        1499  Product_0499  Electronics   779.37

[91 rows x 4 columns]

In [52]:
# Products by 'Home' category

df_home_category = df_products[df_products['category'] == 'Home']
df_home_category

     product_id  product_name category    price
6          1007  Product_0007     Home   286.35
7          1008  Product_0008     Home  1944.83
11         1012  Product_0012     Home   342.42
14         1015  Product_0015     Home   244.62
15         1016  Product_0016     Home   147.25
..          ...           ...      ...      ...
484        1485  Product_0485     Home  1498.29
488        1489  Product_0489     Home   739.85
495        1496  Product_0496     Home   397.93
497        1498  Product_0498     Home  1255.77
499        1500  Product_0500     Home   694.04

[94 rows x 4 columns]

In [53]:
# Products by 'Books' category

df_books_category = df_products[df_products['category'] == 'Books']
df_books_category

     product_id  product_name category    price
2          1003  Product_0003    Books  1776.68
3          1004  Product_0004    Books  1624.45
9          1010  Product_0010    Books  1844.19
29         1030  Product_0030    Books   937.97
35         1036  Product_0036    Books  1684.93
..          ...           ...      ...      ...
462        1463  Product_0463    Books  1745.70
469        1470  Product_0470    Books   632.86
473        1474  Product_0474    Books   384.14
487        1488  Product_0488    Books   643.72
494        1495  Product_0495    Books   774.91

[93 rows x 4 columns]

In [ ]:
# Concatenation of product by categories dataframes

df_concat_product_categories = pd.concat([df_books_category, df_clothing_category, df_electronics_category, df_sports_category, df_home_category], axis = 0)
df_concat_product_categories.sort_values(by = 'product_id', ascending = True)

     product_id  product_name     category    price
0          1001  Product_0001       Sports  1282.68
1          1002  Product_0002       Sports   407.06
2          1003  Product_0003        Books  1776.68
3          1004  Product_0004        Books  1624.45
4          1005  Product_0005       Sports   702.38
..          ...           ...          ...      ...
495        1496  Product_0496         Home   397.93
496        1497  Product_0497  Electronics   527.48
497        1498  Product_0498         Home  1255.77
498        1499  Product_0499  Electronics   779.37
499        1500  Product_0500         Home   694.04

[500 rows x 4 columns]

In [ ]:
# Check if number of rows is equal to 500 and if there are null values after concatenation

df_concat_product_categories.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 2 to 499
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    int64
 1   product_name  500 non-null    object
 2   category      500 non-null    object
 3   price         500 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 19.5+ KB

In [ ]:
# Check if the output of concatenation is similar to 'products' dataframe

df_products

     product_id  product_name     category    price
0          1001  Product_0001       Sports  1282.68
1          1002  Product_0002       Sports   407.06
2          1003  Product_0003        Books  1776.68
3          1004  Product_0004        Books  1624.45
4          1005  Product_0005       Sports   702.38
..          ...           ...          ...      ...
495        1496  Product_0496         Home   397.93
496        1497  Product_0497  Electronics   527.48
497        1498  Product_0498         Home  1255.77
498        1499  Product_0499  Electronics   779.37
499        1500  Product_0500         Home   694.04

[500 rows x 4 columns]

In [88]:
# Further Analysis

# Which category generated the highest revenue?

df_master_dataset.groupby('category').agg({'total_sales':'sum'}).sort_values(by = 'total_sales', ascending = False).iloc[:1]

          total_sales
category
Sports    66356844.05

In [86]:
# Which customer spent the most money?

df_top_10_spenders.iloc[:1]

               total_sales
customer_name
Customer_0153    544534.24

In [ ]:
# What is the average order value? (Formula: Total Revenue / Number of Orders)

#Considering that the sales is only the source of revenue.

avg_order_value = df_master_dataset['total_sales'].sum()/df_master_dataset['order_id'].count()
avg_order_value

2941.5998688

In [120]:
# Which city generated the highest revenue?

df_master_dataset.groupby('city').agg({'total_sales':'sum'}).iloc[:1]

         total_sales
city
Chicago  36507521.31

In [122]:
# What are the monthly sales trends?

month_order = [
    "January", "February", "March", "April",
    "May", "June", "July", "August",
    "September", "October", "November", "December"
]

df_master_dataset['order_month'] = df_master_dataset['order_date'].dt.month_name()
df_master_dataset['order_month'] = pd.Categorical(df_master_dataset['order_month'], categories = month_order, ordered = True)
df_master_dataset.groupby('order_month', observed = True).agg({'total_sales':'sum'})

             total_sales
order_month
January      24759276.57
February     22612425.65
March        25538147.84
April        23716648.96
May          24229490.19
June         23677947.80
July         23736789.78
August       25671530.78
September    24103131.22
October      25464296.86
November     24115106.16
December     26535195.07